import {pilotPrices,vehicles,paintColors,wheelNames,spoilerNames} from '../dist/catalog.js';
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json','Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});
const problem=(message,status=400)=>{const e=new Error(message);e.status=status;throw e};
function database(env){if(!env.DB)problem('A garagem está temporariamente indisponível. Tente novamente.',503);return env.DB}
async function readProfile(db,id){const profile=await db.prepare('SELECT nickname,coins,created_at FROM profiles WHERE user_id=?').bind(id).first();if(!profile)return null;const [o,g,r]=await Promise.all([db.prepare('SELECT kind,item_id FROM owned_items WHERE user_id=?').bind(id).all(),db.prepare('SELECT pilot,vehicle,paint,wheels,spoiler FROM garages WHERE user_id=?').bind(id).first(),db.prepare('SELECT track,mode,time FROM race_records WHERE user_id=?').bind(id).all()]);return {...profile,owned:o.results,garage:g,records:Object.fromEntries(r.results.map(x=>[x.track+'-'+x.mode,x.time]))}}
async function body(req){if(Number(req.headers.get('content-length')||0)>6000)problem('Pedido muito grande.',413);let raw=await req.text();if(raw.length>6000)problem('Pedido muito grande.',413);try{return JSON.parse(raw)}catch{problem('Pedido inválido.')}}
function validNumber(value,min,max){return Number.isInteger(value)&&value>=min&&value<=max}
export async function handleAPI(req,env){try{const url=new URL(req.url),id=req.headers.get('oai-authenticated-user-id');if(!id)return json({error:'Entre com ChatGPT para salvar sua garagem.',signin:'/signin-with-chatgpt?return_to=/'},401);const db=database(env);const path=url.pathname;
if(req.method==='GET'&&path==='/api/profile')return json({signedIn:true,profile:await readProfile(db,id)});
if(req.method!=='POST')return json({error:'Rota não encontrada.'},404);
if(req.headers.get('origin')&&req.headers.get('origin')!==url.origin)return json({error:'Origem inválida.'},403);if(req.headers.get('sec-fetch-site')==='cross-site')return json({error:'Origem inválida.'},403);
const b=await body(req),now=Date.now();
if(path==='/api/profile'){const name=String(b.nickname||'').trim();if(!/^[\p{L}\p{N} _.-]{3,20}$/u.test(name))problem('Use 3 a 20 letras, números, espaços ou _.- no nome.');await db.batch([db.prepare('INSERT INTO profiles(user_id,nickname,coins,created_at) VALUES(?,?,600,?) ON CONFLICT(user_id) DO UPDATE SET nickname=excluded.nickname').bind(id,name,now),db.prepare('INSERT INTO garages(user_id) VALUES(?) ON CONFLICT(user_id) DO NOTHING').bind(id)]);return json({profile:await readProfile(db,id)})}
const profile=await readProfile(db,id);if(!profile)problem('Crie seu perfil de piloto primeiro.',409);
const owns=(kind,item)=>kind==='pilot'?pilotPrices[item]===0||profile.owned.some(x=>x.kind===kind&&x.item_id===item):item===0||profile.owned.some(x=>x.kind===kind&&x.item_id===item);
if(path==='/api/purchase'){const kind=b.kind,item=b.item;if(!['pilot','vehicle'].includes(kind)||!validNumber(item,0,kind==='pilot'?pilotPrices.length-1:vehicles.length-1))problem('Item inválido.');if(owns(kind,item))return json({profile,alreadyOwned:true});const price=kind==='pilot'?pilotPrices[item]:vehicles[item].price;if(profile.coins<price)problem('Você precisa de mais moedas para esse item.',409);
const result=await db.batch([db.prepare('UPDATE profiles SET coins=coins-? WHERE user_id=? AND coins>=? AND NOT EXISTS(SELECT 1 FROM owned_items WHERE user_id=? AND kind=? AND item_id=?)').bind(price,id,price,id,kind,item),db.prepare('INSERT INTO owned_items(user_id,kind,item_id,acquired_at) SELECT ?,?,?,? WHERE changes()>0 ON CONFLICT(user_id,kind,item_id) DO NOTHING').bind(id,kind,item,now)]);if(!result[0].meta.changes)problem('Saldo ou garagem mudou. Atualize e tente novamente.',409);return json({profile:await readProfile(db,id)})}
if(path==='/api/garage'){if(!validNumber(b.pilot,0,pilotPrices.length-1)||!validNumber(b.vehicle,0,vehicles.length-1)||!paintColors.includes(b.paint)||!validNumber(b.wheels,0,wheelNames.length-1)||!validNumber(b.spoiler,0,spoilerNames.length-1))problem('Personalização inválida.');if(!owns('pilot',b.pilot)||!owns('vehicle',b.vehicle))problem('Esse item ainda não está na sua garagem.',403);await db.prepare('UPDATE garages SET pilot=?,vehicle=?,paint=?,wheels=?,spoiler=? WHERE user_id=?').bind(b.pilot,b.vehicle,b.paint,b.wheels,b.spoiler,id).run();return json({profile:await readProfile(db,id)})}
if(path==='/api/race/start'){if(!validNumber(b.track,0,8)||!['race','time'].includes(b.mode)||!validNumber(b.pilot,0,11)||!validNumber(b.vehicle,0,5)||!owns('pilot',b.pilot)||!owns('vehicle',b.vehicle))problem('Configuração de corrida inválida.');const active=await db.prepare('SELECT id FROM race_runs WHERE user_id=? AND completed_at IS NULL AND started_at>?').bind(id,now-1000).first();if(active)problem('Uma corrida já está iniciando. Tente novamente.',429);const ticket=crypto.randomUUID();await db.prepare('INSERT INTO race_runs(id,user_id,track,mode,started_at) VALUES(?,?,?,?,?)').bind(ticket,id,b.track,b.mode,now).run();return json({ticket})}
if(path==='/api/race/finish'){if(typeof b.ticket!=='string'||!Number.isFinite(b.time)||b.time<32||b.time>1500||!validNumber(b.position,1,8)||!validNumber(b.stars,0,84))problem('Resultado inválido.');const run=await db.prepare('SELECT track,mode,started_at,completed_at,reward FROM race_runs WHERE id=? AND user_id=?').bind(b.ticket,id).first();if(!run)problem('Corrida não encontrada.',404);if(run.completed_at!==null)return json({profile,earned:run.reward,alreadySaved:true});if(now-run.started_at<(b.time-2)*1000||now-run.started_at>3600000)problem('Não foi possível validar o tempo da corrida.',409);const reward=85+b.stars*4+(run.mode==='race'?Math.max(0,90-(b.position-1)*15):40);
await db.batch([db.prepare('UPDATE race_runs SET completed_at=?,time=?,position=?,stars=?,reward=? WHERE id=? AND user_id=? AND completed_at IS NULL').bind(now,b.time,b.position,b.stars,reward,b.ticket,id),db.prepare('UPDATE profiles SET coins=coins+? WHERE user_id=? AND changes()>0').bind(reward,id),db.prepare('INSERT INTO race_records(user_id,track,mode,time) VALUES(?,?,?,?) ON CONFLICT(user_id,track,mode) DO UPDATE SET time=MIN(race_records.time,excluded.time)').bind(id,run.track,run.mode,b.time)]);return json({profile:await readProfile(db,id),earned:reward})}
return json({error:'Rota não encontrada.'},404)
}catch(e){if(!e.status)console.error('Kart API failed',e.message);return json({error:e.status?e.message:'Não foi possível salvar agora. Tente novamente.'},e.status||503)}}
export default {async fetch(req,env){const url=new URL(req.url);if(url.pathname.startsWith('/api/'))return handleAPI(req,env);if(req.method!=='GET'&&req.method!=='HEAD')return new Response('Method not allowed',{status:405});const key=url.pathname==='/'?'/index.html':url.pathname,asset=ASSET_BYTES[key];if(!asset)return new Response('Not found',{status:404});const bytes=Uint8Array.from(atob(asset.data),c=>c.charCodeAt(0));return new Response(req.method==='HEAD'?null:bytes,{headers:{'Content-Type':asset.type,'Cache-Control':key.endsWith('.html')||key.endsWith('sw.js')?'no-cache':'public, max-age=300','X-Content-Type-Options':'nosniff'}})}};
